name: Build and Deploy

on: 
  push:
    tags:
      - 'v*'

jobs:
    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notifier:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notifier:${{ github.sha }}

        - name: Trigger Portainer Webhook
          run: |
            curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}?IMAGE_TAG=${{ github.sha }}
